### ISSUE TITLE
Typo about the "Access_Key" and "http_sd_config"

### ISSUE THREAD

**Issue by jmbourdaret** [promhippie/prometheus-scw-sd#106]
## 1st error : **ACCESS_KEY**
Error
```json
{"level":"error","msg":"Missing any credentials","ts":"2022-07-11T11:33:03.961864062Z"}
```
shows up even when the configuration environments variables are set.

Documentation (https://promhippie.github.io/prometheus-scw-sd/#getting-started)  tells about configuration of the service with the variable 
```
PROMETHEUS_SCW_ACCESS_KEY
```
When the code https://github.com/promhippie/prometheus-scw-sd/blob/b53aaf7918358c76058316a272490e072d408180/pkg/command/server.go#L153 is actually waiting for `PROMETHEUS_SCW_ACESS_KEY` , **ACESS** instead of **ACCESS**.

Also, the error message is a bit misleading, it tells us it is missing _any credentials_, casting doubt on all the process of configuration;  when actually only one credential is missing. 

## 2nd typo: **http_sd_config**
Documentation https://promhippie.github.io/prometheus-scw-sd/#getting-started is describing how to set up ServiceDiscovery  https://github.com/promhippie/prometheus-scw-sd/blob/b53aaf7918358c76058316a272490e072d408180/docs/content/getting-started.md?plain=1#L148
The syntax should be `http_sd_configs` (plural) instead of  `http_sd_config`. 

Thanks for this piece of software ! I'm eager to use it !

**Comment by tboerger** [comment]
The error message has not improved yet, but the typos are resolved. Thanks for the report.
